--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WolfDen133/WFT
build-by-default: true
branches:
- main
projects:
  WFT:
    path: ""
    icon: "logo.png"
    libs:
      - src: ACM-Pocketmine-MP/Commando/Commando
        version: ^3.2.1
    lint:
      phpstan: false
...
